services:
  api:
    image: donrodriguez/passive-logic-web-api:0.0.0
    container_name: api
    build:
      context: ../PhysicsSimulationWebApi/API
      dockerfile: Dockerfile
    ports:
      - "5293:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
#      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  web-app:
    image: donrodriguez/passivelogic-physics-simulator-web-app:0.0.0
    container_name: web-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge